---
title: "Data Visualization"
author: "Erica Bishop"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(sf)
```

## Task 1: Bad data viz

```{r}
space_launches <- read_csv(here("data", "space_launches.csv"))

```

```{r}
space_lunch <- space_launches |> 
  separate(col = type, into = "vehicle_type", sep = " ", remove = FALSE)

ggplot(data = space_lunch, aes(x = launch_date,
                          y = vehicle_type)) +
  geom_jitter(size = 0.25) +
  #scale_color_discrete(name = category, hue =  "white", "red", "steelblue3") +
    labs(x = "DATE OF LAUNCH",
       y = "SPACE VEHICLE",
      title = "WHAT'S IN SPACE?") +
  theme(plot.background = element_rect(fill = "darkblue"),
        panel.background = element_rect(fill = "darkblue"),
        plot.title = element_text(hjust = 0.5, color = "ghostwhite"),
        axis.title.x = element_text(color = "ghostwhite"),
        axis.title.y = element_text(color = "ghostwhite"),
        panel.grid = element_blank()) +
    annotate("text", x = 500, y = 10, label = "ROCKETS!", color = "deeppink")

```
```{r}
ggsave(here("rockets_graph.png"))
```

##Task 2

```{r}
sf_gg <- read_csv(here("data", "San_Francisco_Communitywide_Greenhouse_Gas_Inventory.csv"))


```

```{r}

summary_table <- sf_gg |>
  group_by(Sector_General) |> 
  summarize(total_ghg = sum(Emissions_mtCO2e, na.rm = TRUE))

summary_table2 <- sf_gg |> 
  group_by(Calendar_Year, Commodity_Type) |> 
  summarize(ghg_total = sum(Emissions_mtCO2e, na.rm = TRUE))
  
subset <- sf_gg |> 
  filter(Calendar_Year %in% 2002) |> 
  select()


```



```{r}

ggplot(data = summary_table2,
       aes(x = Calendar_Year,
           y = ghg_total)) +
  geom_jitter() +
  gghighlight(Commodity_Type == "Electricity",
            label_key = Commodity_Type)





```




